name: Mundo Azul API Comum

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello-ma:
    runs-on: ububtu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Executar Build
        run: echo "Buildando projeto java...."

      - name: "Executar Deploy"
        run: |
          echo "Realizando o deploy ${{ runner.os }}"
          echo "Diretorio atual: $(pwd)"
          echo "Data atual: ${date}"
          echo "Usuario: $(whoami)"

      - name: Listar workspace
        run: ls -lta

      - name: Clear WorkSpace
        run: |
          echo "Limpando WorkSpace"
          echo "API já disponível para utilização"
          echo "Worfklow realizado com SUCESSO"
